[package]
name = "halo2-dynamic-sha256"
version = "0.1.0"
edition = "2018"
authors = ["Sora Suegami"]
description = "SHA256 verification circuit in halo2 supporting dynamic length input."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
halo2wrong = { git = "https://github.com/privacy-scaling-explorations/halo2wrong", version = "0.1.0" }
maingate = { git = "https://github.com/privacy-scaling-explorations/halo2wrong", version = "0.1.0" }

[dev-dependencies]
criterion = "0.3"
rand = "0.8.4"

[[bench]]
name = "digest"
harness = false
